package io.labdeck.manifest;

public enum ManifestProblemCode {
    MANIFEST_PARSE_ERROR,
    MANIFEST_SCHEMA_VERSION_UNSUPPORTED,
    MANIFEST_UNKNOWN_FIELD,
    MANIFEST_REQUIRED_FIELD_MISSING,
    MANIFEST_VALUE_TYPE_INVALID,
    MANIFEST_VALUE_INVALID,
    MANIFEST_PRIVILEGED_FORBIDDEN,
    MANIFEST_HOST_NAMESPACE_FORBIDDEN,
    MANIFEST_DOCKER_SOCKET_FORBIDDEN,
    MANIFEST_SENSITIVE_MOUNT_FORBIDDEN,
    MANIFEST_DEVICE_FORBIDDEN,
    MANIFEST_CAPABILITY_FORBIDDEN,
    MANIFEST_ESCAPE_OPTION_FORBIDDEN,
    MANIFEST_TRAVERSAL_FORBIDDEN,
    MANIFEST_HOST_PATH_FORBIDDEN,
    MANIFEST_SHELL_COMMAND_FORBIDDEN,
    MANIFEST_IMAGE_INVALID,
    MANIFEST_MUTABLE_IMAGE_TAG_FORBIDDEN,
    MANIFEST_PORT_POLICY_VIOLATION,
    MANIFEST_RESOURCE_LIMIT_INVALID
}
