package io.labdeck.lab;

public enum LabFailureCode {
    DOCKER_UNAVAILABLE,
    HOST_PORT_IN_USE,
    CONTAINER_START_FAILED,
    CONTAINER_EXITED,
    HEALTHCHECK_UNHEALTHY,
    STARTUP_TIMEOUT,
    OWNERSHIP_MISMATCH,
    CLEANUP_INCOMPLETE
}
